deploy: deployFollowSystem deployTweetContract

deployFollowSystem:
	npx hardhat run scripts/deployFollowSystem.ts --network localhost

deployTweetContract:
	npx hardhat run scripts/deployTweetContract.ts --network localhost
